module.exports = {
    name : 'categories',
    attrs: {
        lib : {type:'string'}
    },
    methods: {
        test : function(){
            return this.lib.substr(0, 3);
        }
    },
    data :[
        {lib : 'Classic Rock'},
        {lib : 'Country'},
        {lib : 'Dance'},
        {lib : 'Disco'},
        {lib : 'Funk'},
        {lib : 'Grunge'},
        {lib : 'Hip-Hop'},
        {lib : 'Jazz'},
        {lib : 'Metal'},
        {lib : 'New Age'},
        {lib : 'Oldies'},
        {lib : 'Pop'},
        {lib : 'R&B'},
        {lib : 'Rap'},
        {lib : 'Reggae'},
        {lib : 'Rock'},
        {lib : 'Techno'},
        {lib : 'Industrial'},
        {lib : 'Alternative'},
        {lib : 'Ska'},
        {lib : 'Death Metal'},
        {lib : 'Pranks'},
        {lib : 'Soundtrack'},
        {lib : 'Euro-Techno'},
        {lib : 'Ambient'},
        {lib : 'Trip-Hop'},
        {lib : 'Vocal'},
        {lib : 'Jazz+Funk'},
        {lib : 'Fusion'},
        {lib : 'Trance'},
        {lib : 'Classical'},
        {lib : 'Instrumental'},
        {lib : 'Acid'},
        {lib : 'House'},
        {lib : 'Game'},
        {lib : 'Sound Clip'},
        {lib : 'Gospel'},
        {lib : 'Noise'},
        {lib : 'Alternative Rock'},
        {lib : 'Bass'},
        {lib : 'Soul'},
        {lib : 'Punk'},
        {lib : 'Space'},
        {lib : 'Meditative'},
        {lib : 'Instrumental Pop'},
        {lib : 'Instrumental Rock'},
        {lib : 'Ethnic'},
        {lib : 'Gothic'},
        {lib : 'Darkwave'},
        {lib : 'Techno-Industrial'},
        {lib : 'Electronic'},
        {lib : 'Pop-Folk'},
        {lib : 'Eurodance'},
        {lib : 'Dream'},
        {lib : 'Southern Rock'},
        {lib : 'Comedy'},
        {lib : 'Cult'},
        {lib : 'Gangsta'},
        {lib : 'Top 40'},
        {lib : 'Christian Rap'},
        {lib : 'Pop/Funk'},
        {lib : 'Jungle'},
        {lib : 'Native US'},
        {lib : 'Cabaret'},
        {lib : 'New Wave'},
        {lib : 'Psychadelic'},
        {lib : 'Rave'},
        {lib : 'Showtunes'},
        {lib : 'Trailer'},
        {lib : 'Lo-Fi'},
        {lib : 'Tribal'},
        {lib : 'Acid Punk'},
        {lib : 'Acid Jazz'},
        {lib : 'Polka'},
        {lib : 'Retro'},
        {lib : 'Musical'},
        {lib : 'Rock & Roll'},
        {lib : 'Hard Rock'},
        {lib : 'Folk'},
        {lib : 'Folk-Rock'},
        {lib : 'National Folk'},
        {lib : 'Swing'},
        {lib : 'Fast Fusion'},
        {lib : 'Bebob'},
        {lib : 'Latin'},
        {lib : 'Revival'},
        {lib : 'Celtic'},
        {lib : 'Bluegrass'},
        {lib : 'Avantgarde'},
        {lib : 'Gothic Rock'},
        {lib : 'Progressive Rock'},
        {lib : 'Psychedelic Rock'},
        {lib : 'Symphonic Rock'},
        {lib : 'Slow Rock'},
        {lib : 'Big Band'},
        {lib : 'Chorus'},
        {lib : 'Easy Listening'},
        {lib : 'Acoustic'},
        {lib : 'Humour'},
        {lib : 'Speech'},
        {lib : 'Chanson'},
        {lib : 'Opera'},
        {lib : 'Chamber Music'},
        {lib : 'Sonata'},
        {lib : 'Symphony'},
        {lib : 'Booty Bass'},
        {lib : 'Primus'},
        {lib : 'Porn Groove'},
        {lib : 'Satire'},
        {lib : 'Slow Jam'},
        {lib : 'Club'},
        {lib : 'Tango'},
        {lib : 'Samba'},
        {lib : 'Folklore'},
        {lib : 'Ballad'},
        {lib : 'Power Ballad'},
        {lib : 'Rhythmic Soul'},
        {lib : 'Freestyle'},
        {lib : 'Duet'},
        {lib : 'Punk Rock'},
        {lib : 'Drum Solo'},
        {lib : 'Acapella'},
        {lib : 'Euro-House'},
        {lib : 'Dance Hall'},
        {lib : 'Goa'},
        {lib : 'Drum & Bass'},
        {lib : 'Club - House'},
        {lib : 'Hardcore'},
        {lib : 'Terror'},
        {lib : 'Indie'},
        {lib : 'BritPop'},
        {lib : 'Negerpunk'},
        {lib : 'Polsk Punk'},
        {lib : 'Beat'},
        {lib : 'Christian Gangsta Rap'},
        {lib : 'Heavy Metal'},
        {lib : 'Black Metal'},
        {lib : 'Crossover'},
        {lib : 'Contemporary Christian'},
        {lib : 'Christian Rock'},
        {lib : 'Merengue'},
        {lib : 'Salsa'},
        {lib : 'Thrash Metal'},
        {lib : 'Anime'},
        {lib : 'JPop'},
        {lib : 'Synthpop'},
        {lib : 'Autre'}
    ]

};